### PR TITLE
Resolved clang-tidy warnings

### LINKED ISSUE #40: [BUG]: CI pipeline fails at ROS Industrial
### Issue Description

The CI pipeline fails when testing the implementation for all versions of the project.

### Steps to Reproduce

The reference pipeline may be observed [here](https://github.com/evan-palmer/blue/actions/runs/5406987761/jobs/9824475362).

### Expected Behavior

The CI pipeline should pass.

### Error Message

```bash
- pep257
  <<< failure message
    -- run_test.py: invoking following command in '/root/target_ws/src/blue/blue_control':
     - /opt/ros/rolling/bin/ament_pep257 --xunit-file /root/target_ws/build/blue_control/test_results/blue_control/pep257.xunit.xml
    checking ./launch/control.launch.py
    ./launch/control.launch.py:28 in public function `generate_launch_description`: D213: Multi-line docstring summary should start at the second line
    ./launch/control.launch.py:28 in public function `generate_launch_description`: D413: Missing blank line after last section ('Returns')
    ./launch/control.launch.py:28 in public function `generate_launch_description`: D407: Missing dashed underline after section ('Returns')
    ./launch/control.launch.py:28 in public function `generate_launch_description`: D406: Section name should end with a newline ('Returns', not 'Returns:')
    4 errors
    -- run_test.py: return code 1
    -- run_test.py: verify result file '/root/target_ws/build/blue_control/test_results/blue_control/pep257.xunit.xml'
  >>>
build/blue_control/test_results/blue_control/pep257.xunit.xml: 4 tests, 0 errors, 4 failures, 0 skipped
- blue_control.pep257 D213 (./launch/control.launch.py:28)
  <<< failure message
    D213: Multi-line docstring summary should start at the second line
  >>>
- blue_control.pep257 D413 (./launch/control.launch.py:28)
  <<< failure message
    D413: Missing blank line after last section ('Returns')
  >>>
- blue_control.pep257 D407 (./launch/control.launch.py:28)
  <<< failure message
    D407: Missing dashed underline after section ('Returns')
  >>>
- blue_control.pep257 D406 (./launch/control.launch.py:28)
  <<< failure message
    D406: Section name should end with a newline ('Returns', not 'Returns:')
  >>>
build/blue_utils/Testing/20230629-0022/Test.xml: 4 tests, 0 errors, 1 failure, 0 skipped
- cpplint
  <<< failure message
    -- run_test.py: invoking following command in '/root/target_ws/src/blue/blue_utils':
     - /opt/ros/rolling/bin/ament_cpplint --xunit-file /root/target_ws/build/blue_utils/test_results/blue_utils/cpplint.xunit.xml
    Using '--root=/root/target_ws/src/blue/blue_utils/include' argument
    
    Done processing /root/target_ws/src/blue/blue_utils/include/blue_utils/eigen.hpp
    
    /root/target_ws/src/blue/blue_utils/include/blue_utils/tf2.hpp:90:  For a static/global string constant, use a C style string instead: "const char kMapFrameId[]".  [runtime/string] [4]
    /root/target_ws/src/blue/blue_utils/include/blue_utils/tf2.hpp:91:  For a static/global string constant, use a C style string instead: "const char kMapNedFrameId[]".  [runtime/string] [4]
    /root/target_ws/src/blue/blue_utils/include/blue_utils/tf2.hpp:92:  For a static/global string constant, use a C style string instead: "const char kBaseLinkFrameId[]".  [runtime/string] [4]
    /root/target_ws/src/blue/blue_utils/include/blue_utils/tf2.hpp:93:  For a static/global string constant, use a C style string instead: "const char kBaseLinkFrdFrameId[]".  [runtime/string] [4]
    Done processing /root/target_ws/src/blue/blue_utils/include/blue_utils/tf2.hpp
    
    Category 'runtime/string' errors found: 4
    Total errors found: 4
    -- run_test.py: return code 1
    -- run_test.py: verify result file '/root/target_ws/build/blue_utils/test_results/blue_utils/cpplint.xunit.xml'
  >>>
build/blue_utils/test_results/blue_utils/cpplint.xunit.xml: 5 tests, 0 errors, 4 failures, 0 skipped
- blue_utils.cpplint runtime/string [4] (/root/target_ws/src/blue/blue_utils/include/blue_utils/tf2.hpp:90)
  <<< failure message
    For a static/global string constant, use a C style string instead: "const char kMapFrameId[]".
  >>>
- blue_utils.cpplint runtime/string [4] (/root/target_ws/src/blue/blue_utils/include/blue_utils/tf2.hpp:91)
  <<< failure message
    For a static/global string constant, use a C style string instead: "const char kMapNedFrameId[]".
  >>>
- blue_utils.cpplint runtime/string [4] (/root/target_ws/src/blue/blue_utils/include/blue_utils/tf2.hpp:92)
  <<< failure message
    For a static/global string constant, use a C style string instead: "const char kBaseLinkFrameId[]".
  >>>
- blue_utils.cpplint runtime/string [4] (/root/target_ws/src/blue/blue_utils/include/blue_utils/tf2.hpp:93)
  <<< failure message
    For a static/global string constant, use a C style string instead: "const char kBaseLinkFrdFrameId[]".
  >>>
```

### Runtime Environment

This error occurs when running on the GitHub servers.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by evan-palmer**
# Checklist

- [x] I have performed a thorough review of my code
- [x] I have sufficiently commented my code
- [x] The implementation follows the project style conventions
- [x] All project unit tests are passing
- [x] If relevant, documentation has been provided or updated to discuss the changes made
- [x] System integration tests were performed successfully

## Changes Made

This PR `hopefully` resolves the clang-tidy warnings that are being caught by the CI. Furthermore, the CI pipeline was updated to run at PR to avoid discovering issues after push.

## Associated Issues

- Fixes #40 

## Testing

colcon tests were run in addition to regression tests in SITL.

### CODE REVIEW

File: blue_dynamics/src/hydrodynamics.cpp [hunk 1]
```diff
@@ -60,7 +60,7 @@ Coriolis::Coriolis(
   const Eigen::Vector6d & added_mass_coeff)
```
Comment (evan-palmer) [inline blue_dynamics/src/hydrodynamics.cpp:60]: The constructors should probably be updated to use `std::move` instead of passing a const ref.
